language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8
  - oraclejdk8

script:
  - mvn clean verify coveralls:report

deploy:
  provider: script
  script: mvn clean deploy --settings=".travis.settings.xml"
  on:
    tags: true
    jdk: oraclejdk8
